title: TED Year In Review
email: anand.upender@gmail.com
# analytics: UA-40781755-2
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

include: ['_pages']

# Build settings
markdown: kramdown
sass:
  style: compressed
plugins:
  - jekyll-feed